import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { INVEXA_LOGO_BASE64 } from "../assets/logoBase64";
import { apiFetch } from "../api/client";

type Holding = {
  ticker: string;
  quantity: number;
  avgCost: number;
  livePrice: number;
  marketValue: number;
  unrealizedPnl: number;
};

type Input = {
  user: { id: string; username: string; email: string };
  token: string;
  portfolio?: {
    totalHoldingsValue: number;
    holdings: Holding[];
  };
};

function inr(n: number) {
  return "Rs. " + n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

async function fetchSector(ticker: string, token: string): Promise<string> {
  try {
    const profile = await apiFetch<{ sector?: string }>(`/stocks/${ticker}/profile`, {}, token);
    return profile.sector || "N/A";
  } catch {
    return "N/A";
  }
}

export async function downloadPortfolioHoldingsPdf({ user, token, portfolio }: Input) {
  const holdings = portfolio?.holdings ?? [];
  const totalValue = portfolio?.totalHoldingsValue ?? 0;

  // Sector lookups are cached server-side (24h), so this is cheap even for a
  // decent-sized portfolio.
  const sectors = await Promise.all(holdings.map((h) => fetchSector(h.ticker, token)));

  const doc = new jsPDF({ unit: "pt", format: "a4", orientation: holdings.length > 0 ? "landscape" : "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  doc.addImage(INVEXA_LOGO_BASE64, "PNG", margin, 28, 40, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Invexa", margin + 50, 48);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  doc.text("Portfolio Holdings", margin + 50, 63);

  doc.setDrawColor(220);
  doc.line(margin, 82, pageWidth - margin, 82);

  doc.setTextColor(20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Account Holder: ${user.username}`, margin, 102);
  doc.text(`Account ID: ${user.id}`, margin, 116);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}`, margin, 130);

  if (holdings.length === 0) {
    doc.setFontSize(11);
    doc.text("No stocks currently held in the portfolio.", margin, 160);
  } else {
    autoTable(doc, {
      startY: 150,
      margin: { left: margin, right: margin },
      head: [["Sr.No", "Scrip Name", "CMP", "Qty", "Avg Cost", "Mkt Val", "Investment", "Unrealised Gain/Loss", "Sector", "Weightage(%)"]],
      body: holdings.map((h, idx) => {
        const investment = h.avgCost * h.quantity;
        const weightage = totalValue > 0 ? (h.marketValue / totalValue) * 100 : 0;
        return [
          String(idx + 1),
          h.ticker,
          inr(h.livePrice),
          String(h.quantity),
          inr(h.avgCost),
          inr(h.marketValue),
          inr(investment),
          (h.unrealizedPnl >= 0 ? "+" : "") + inr(h.unrealizedPnl),
          sectors[idx],
          `${weightage.toFixed(2)}%`
        ];
      }),
      theme: "striped",
      headStyles: { fillColor: [17, 20, 23], textColor: 255, fontStyle: "bold", fontSize: 9 },
      styles: { fontSize: 8.5, cellPadding: 6, overflow: "linebreak", valign: "top" },
      // Keep a row intact on one page instead of letting a wrapped cell (e.g. a
      // long sector name) split across a page break.
      rowPageBreak: "avoid",
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 7) {
          const raw = holdings[data.row.index]?.unrealizedPnl ?? 0;
          data.cell.styles.textColor = raw >= 0 ? [31, 157, 110] : [209, 60, 60];
        }
      }
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      "This is a virtual paper-trading statement generated by Invexa. No real currency is involved.",
      margin,
      doc.internal.pageSize.getHeight() - 20
    );
  }

  doc.save(`invexa-holdings-${user.username}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
